### ISSUE TITLE
returns Invalid server specification: while doing  mitmdump -s mitm.py --mode

### ISSUE THREAD

**Issue by Sunda001** [Zelak312/flaresolverr-mitm-proxy#11]
![image](https://github.com/Zelak312/flaresolverr-mitm-proxy/assets/32301831/abb5e000-e65a-4918-85c5-2c08af64e021)

**Comment by Zelak312** [comment]
Seems like mitmdump doesn't directly support user and password authentication in the url in the mode parameter. From the documentation, it seems upstream_auth will do the trick https://docs.mitmproxy.org/stable/concepts-options/#upstream_auth

Can you try

`mitmdump -s mitm.py --mode upstream:http://localhost:8080 --upstream-auth sakty:151101sakty`

Also make sure, I didn't do errors in the proxy url, port, user and password.

If that doesn't work, the mitmproxy documentation should be looked at to know how to use auth for upstream proxy, it isn't an issue directly with flaresolverr-mitm-proxy

Something to note as well. Mitmdump runs on port 8080 by default as specified by https://docs.mitmproxy.org/stable/concepts-options/#listen_port. So if you really have a proxy server running on localhost port 8080 you may have to change the port of one of them. For mitmdump it's `--listen-port 8090` for example

**Comment by Sunda001** [comment]
![image](https://github.com/Zelak312/flaresolverr-mitm-proxy/assets/32301831/3433990a-2eed-4ec3-946b-996728f5b806)


> Seems like mitmdump doesn't directly support user and password authentication in the url in the mode parameter. From the documentation, it seems upstream_auth will do the trick https://docs.mitmproxy.org/stable/concepts-options/#upstream_auth
> 
> Can you try
> 
> `mitmdump -s mitm.py --mode upstream:http://localhost:8080 --upstream-auth sakty:151101sakty`
> 
> Also make sure, I didn't do errors in the proxy url, port, user and password.
> 
> If that doesn't work, the mitmproxy documentation should be looked at to know how to use auth for upstream proxy, it isn't an issue directly with flaresolverr-mitm-proxy
> 
> Something to note as well. Mitmdump runs on port 8080 by default as specified by https://docs.mitmproxy.org/stable/concepts-options/#listen_port. So if you really have a proxy server running on localhost port 8080 you may have to change the port of one of them. For mitmdump it's `--listen-port 8090` for example

**Comment by Sunda001** [comment]
does it mean work?

**Comment by Sunda001** [comment]
![image](https://github.com/Zelak312/flaresolverr-mitm-proxy/assets/32301831/ec075917-d3d0-43d3-817b-bd599a4fd2ad)
dunno why it doesnt work

**Comment by Sunda001** [comment]
ah its working when i use my  server ip instead of localhost

**Comment by Sunda001** [comment]
i think i have to run it on the docker right?

**Comment by Zelak312** [comment]
I will have to fix the docker first. Docker presently doesn't work with upstream auth. But it is not a necessity. It depends if you want or not

**Comment by Sunda001** [comment]
ah okay, thank you!
