### ISSUE TITLE
Hope to support Mac m1

### ISSUE THREAD

**Issue by Nuggets1024** [Zelak312/flaresolverr-mitm-proxy#6]
! flaresolverr-mitm-proxy The requested image's platform (linux/amd64) does not match the detected host platform (linux/arm64/v8) and no specific platform was requested

**Comment by Zelak312** [comment]
Normally it should already support ARM64 I believe.
I think it's because I only built the images for AMD64 and none for ARM64

I will look at this tonight and try to include multi-platforms docker images so it builds for ARM64 as well

**Comment by Zelak312** [comment]
I haven't had time to test the image. I don't have any of my ARM machine setup with docker yet. It seems to have built correctly for ARM64
try this version `ghcr.io/zelak312/flaresolverr-mitm-proxy:v1.0.2-alpha` and tell me if it seems to work correctly. Normally this should solve the issue
